/// <summary>
/// Таблица переводов: русский исходник -&gt; английский.
///
/// КАК ДОБАВИТЬ ПЕРЕВОД НОВОЙ РЕПЛИКИ / ЗАДАЧИ / РЕАКЦИИ:
///   1) В коде или префабе пишите русскую строку как обычно
///      (TalkUI.Say("..."), tasksUI.ShowTask("..."), React("..."), и т.п.).
///   2) Добавьте сюда строку  {"та же самая русская строка", "English version"}.
/// Если перевода нет — в EN-режиме просто покажется русский, ничего не сломается.
///
/// ВАЖНО: ключ (левая колонка) должен ПОБУКВЕННО совпадать с тем, что передаётся
/// в показ — включая теги &lt;b&gt;...&lt;/b&gt;, переносы строк \n, пробелы и скобки.
/// </summary>
public static class LocalizationData {
    public static readonly (string ru, string en)[] Pairs = {
        // ───────────────────────── Глава 1: Стол / Радио (StoryManager) ─────────────────────────
        ("\"Феномен меметического гипноза...\"\nХах, ну и бред. Кто вообще верит в такое?",
            "\"The phenomenon of memetic hypnosis...\"\nHah, what nonsense. Who even believes this stuff?"),
        ("\"Такое только мой дядька и читает.\n  Атлантида!.. Планета нибиру...",
            "\"Only my uncle reads stuff like this.\n  Atlantis!.. Planet Nibiru..."),
        ("\"Сам-то в больницу уехал - как на похороны, жутко ему от врачей..\n А я после перелома как новенький!",
            "\"Off to the hospital he went - like to a funeral, the doctors terrify him..\n And me, after a fracture, good as new!"),
        ("\"Поразвлекаюсь пока с его книжками, всё равно он нескоро вернётся.",
            "\"I'll amuse myself with his little books for now, he won't be back for a while anyway."),
        ("Надоели уже эти подкасты, включу ка я лоу-фай",
            "Sick of these podcasts, let me put on some lo-fi"),
        ("Найдите музыкальную волну",
            "Find a music station"),
        ("Найдите музыкальную волну (<b>ПКМ</b> положить предмет)",
            "Find a music station (<b>RMB</b> to put item down)"),
        ("Подпевайте радиостанции (<b>E</b>)",
            "Sing along with the station (<b>E</b>)"),
        ("Щёлкайте в ритм радиостанции (<b>Q</b>)",
            "Snap along to the station's beat (<b>Q</b>)"),
        ("Найду лучше что-то нейтральное",
            "Better find something more neutral"),
        ("Найдите расслабляющую волну",
            "Find a relaxing station"),
        ("То что нужно",
            "Just what I needed"),
        ("Продолжите читать",
            "Keep reading"),
        ("Посмотрите обложку (вращать предмет с зажатой <b>ЛКМ</b>)",
            "Look at the cover (rotate the item holding <b>LMB</b>)"),
        ("Кто это написал вообще?",
            "Who even wrote this?"),
        ("Старое барахло, постоянно ломается",
            "Old junk, always breaking down"),
        ("Восстановите волну",
            "Restore the station"),
        ("Хм, странно",
            "Hm, strange"),
        ("Ладно, почитаю в тишине",
            "Fine, I'll read in silence"),
        ("Выключите радио",
            "Turn off the radio"),
        ("Что?! Почему оно работает?",
            "What?! Why is it still on?"),
        ("Голова начинает кружиться, надо отвлечься",
            "My head's starting to spin, I need to distract myself"),
        ("Отвлекитесь от шума (<b>Q</b>) или (<b>E</b>)",
            "Take your mind off the noise (<b>Q</b>) or (<b>E</b>)"),

        // ───────────────────────── Глава 2: Электричество / Кухня ─────────────────────────
        ("Может кнопка выключения сломалась?",
            "Maybe the power button's broken?"),
        ("Отключите радио от питания (WASD)",
            "Unplug the radio from the power (WASD)"),
        ("Хм, я же точно видел, это радио-провод...",
            "Hm, I could've sworn this was the radio's cord..."),
        ("Отключите РАДИО от питания",
            "Unplug the RADIO from the power"),
        ("Избавьтесь от шума",
            "Get rid of the noise"),
        ("Избавьтесь от шума (1 из 3)",
            "Get rid of the noise (1 of 3)"),
        ("Избавьтесь от шума (2 из 3)",
            "Get rid of the noise (2 of 3)"),
        ("Избавьтесь от шума (3 из 3)",
            "Get rid of the noise (3 of 3)"),

        // ───────────────────────── Глава 3: Разбить радио ─────────────────────────
        ("Снова оно... Как же раскалывается головааа...",
            "It's back... My heaaad is splitting..."),
        ("Найдите способ остановить радио",
            "Find a way to stop the radio"),
        ("Померещилось, но кажется молоток был в прихожей",
            "Must've imagined it, but I think the hammer was in the hallway"),
        ("Пора с ним кончать",
            "Time to finish it off"),
        ("Заткнись",
            "Shut up"),
        ("Заткнись, заткнись, заткнись",
            "Shut up, shut up, shut up"),
        ("АААААААА, неееееет.",
            "AAAAAAAA, noooooo."),

        // ───────────────────────── Глава 4: Чип / Чихание ─────────────────────────
        ("Прочитайте записку.",
            "Read the note."),
        ("Найдите как избавится от чипа.",
            "Find a way to get rid of the chip."),
        ("Заставьте себя чихнуть (1 из 3)",
            "Force yourself to sneeze (1 of 3)"),
        ("Заставьте себя чихнуть (2 из 3)",
            "Force yourself to sneeze (2 of 3)"),
        ("Заставьте себя чихнуть (3 из 3)",
            "Force yourself to sneeze (3 of 3)"),

        // ───────────────────────── Финал ─────────────────────────
        ("Теперь они меня не отследят",
            "Now they won't track me"),
        ("Отправьтесь к дяде.",
            "Head to your uncle's."),
        ("надо добраться до дяди, и поскорее",
            "I need to get to my uncle, and fast"),
        ("Вы спасли свой разум!",
            "You saved your mind!"),
        ("Вы спасли свой разум?",
            "You saved your mind?"),

        // ───────────────────────── Реакции на предметы (префабы, React/ChangeQuest) ─────────────────────────
        ("Транзисторы... Лучше напишите, как вырубить чёртово радио!",
            "Transistors... Better off telling me how to kill that damn radio!"),
        ("Засуньте её поглубже! (ПКМ)",
            "Shove it in deeper! (RMB)"),
        ("Пощекочите себя! (ПКМ)",
            "Tickle yourself! (RMB)"),
        ("Это почерк дяди! Что за?.. Микрочипы? Чихание?",
            "That's my uncle's handwriting! What the?.. Microchips? Sneezing?"),
        ("Хорошая была подушка...",
            "It was a good pillow..."),
        ("У меня аллергия на перец...",
            "I'm allergic to pepper..."),
        ("Вдохните перец! (ПКМ)",
            "Inhale the pepper! (RMB)"),
        ("Чёрт, зря сломал солонку",
            "Damn, broke the salt shaker for nothing"),
        ("Вот откуда дядя набрался страшилок про больницы...",
            "So that's where my uncle got his hospital horror stories..."),

        // ── Реакции-осознания (книги/папки/шкафы/подушки/лабиринт/финал) ──
        ("Одна страннее другой.",
            "One weirder than the last."),
        ("Бредовые записки дядьки…",
            "Uncle's crackpot notes…"),
        ("Жаба… Что за бред?",
            "A toad… What the hell?"),
        ("И давно на ванной замок?",
            "Since when is there a lock on the bathroom?"),
        ("Вот ты где! Попалась!",
            "There you are! Gotcha!"),
        ("Вот же оно!",
            "There it is!"),
        (" Карандаши?! Да должны же где-то быть нормальные подушки!",
            " Pencils?! There've got to be some normal pillows somewhere!"),
        ("Серьёзно?",
            "Seriously?"),
        ("Да почему здесь вообще столько жаб?!",
            "Why are there so many toads here anyway?!"),
        ("Я что, в детском фильме? Только стрёмном!",
            "Am I in a kids' movie? A creepy one, though!"),
        ("Ааа! Как громко!",
            "Aaah! So loud!"),
        ("А ванная где..?",
            "And where's the bathroom..?"),
        ("Вот же... Совсем не помню, куда дел ключи.",
            "Ugh... I don't remember where I put the keys at all."),
        ("я пока не могу покинуть квартиру",
            "I can't leave the apartment yet"),
        ("Издеваетесь?.. Теперь я двигаю мебель щелчками?",
            "Are you kidding me?.. Now I move furniture by snapping my fingers?"),
        ("Так, нет. Здесь что-то поменялось.",
            "Okay, no. Something changed here."),
        ("Просто двор? Просто вечер? Так это квартира свихнулась?",
            "Just a yard? Just evening? So it's the apartment that's lost its mind?"),
        ("Откуда вода? На улице ж нет дождя! Что за дверью?..",
            "Where's the water from? It's not even raining outside! What's behind that door?.."),
        ("Вот она где…",
            "So there it is…"),
        ("Ещё не хватало свет вырубить!",
            "Last thing I need is to cut the power!"),
        ("Что-то у меня с глазами…",
            "Something's wrong with my eyes…"),
        ("Не работает! Надо искать что-то ещё.",
            "Not working! I need to find something else."),
        ("Нет... Голова...",
            "No... My head..."),
        ("Перец, ватная палочка, перо… Перец, ватная палочка, перо…",
            "Pepper, cotton swab, feather… Pepper, cotton swab, feather…"),
        ("Я сам себя не слышу... Нужно немного переждать.",
            "I can't even hear myself... I need to wait it out a bit."),

        // ───────────────────────── Статичный UI (меню / паузы / экраны) ─────────────────────────
        ("Начать игру",
            "Start Game"),
        ("Выйти из игры",
            "Quit Game"),
        ("Выйти",
            "Quit"),
        ("Продолжить",
            "Resume"),
        ("Пауза",
            "Paused"),
        ("Пропустить текст (Пробел)",
            "Skip Text (Space)"),
        ("Играть снова",
            "Play Again"),
        ("Громкость",
            "Volume"),
        // Счётчик коллекции книг: {0} — найдено, {1} — всего
        ("{0} из {1}",
            "{0} of {1}"),
        ("Радиоволна\nзахватила ваш разум",
            "The radio wave\nseized your mind"),

        // ── Экран паузы: подсказка по управлению (EscapePanel/Help, ключи = sourceOverride) ──
        ("Управление",
            "Controls"),
        ("Взаимодействие - ЛКМ\nПоложить предмет - ПКМ\nВращать - зажать ЛКМ\nПропустить текст - Пробел\nЩелчок - Q\nПение - E",
            "Interact - LMB\nPlace Item - RMB\nRotate - Hold LMB\nSkip Text - Space\nClick - Q\nSing - E"),

        // ───────────────────────── Финал: осознание (внутренний монолог ГГ) ─────────────────────────
        (" ...Что?.. Это... всё?",
            " ...What?.. Is that... it?"),
        ("Маленькая дрянь... Это всё из-за неё? Радио… эти комнаты...",
            "This little wretch... It was all because of this? The radio... these rooms..."),
        ("Нет, я же видел это по-настоящему! Я что, схожу с ума?",
            "No, I really saw it all! Am I losing my mind?"),
        ("Я же говорил себе, что это бред. Что дядя просто любит свои теории...",
            "I kept telling myself it was nonsense. That my uncle just loves his theories..."),
        ("Хах, чёрт. А если он был прав?",
            "Hah, damn. What if he was right?"),
        ("А ведь… он был прав! Все эти записки, книжки… Он к чему-то готовился.",
            "But... he really was right! All those notes, those books... He was preparing for something."),
        ("Всё. Хватит. Теперь они меня не отследят. И не будут управлять мной!",
            "That's it. Enough. Now they won't track me. And they won't control me!"),
        ("Нужно к дяде. Срочно! Пока ему тоже не засунули чип в башку!",
            "I have to get to my uncle. Now! Before they shove a chip in his head too!"),

        // ───────────────────────── Финальный диалог с «дядей» (ключи без префикса "ГГ:"/"Дядя:") ─────────────────────────
        ("Дядя?.. Подожди... Ты почему здесь? Я же думал, ты в больнице!",
            "Uncle?.. Wait... Why are you here? I thought you were in the hospital!"),
        ("Тише, тише. Всё нормально.",
            "Easy, easy. Everything's fine."),
        ("Ты не представляешь, что произошло.",
            "You have no idea what happened."),
        ("У меня в голове был чип. Настоящий чип. Я вытащил его.",
            "There was a chip in my head. A real chip. I pulled it out."),
        ("Я знаю.",
            "I know."),
        ("...Что?",
            "...What?"),
        ("…гм.",
            "...hm."),
        ("Продолжай.",
            "Go on."),
        ("Я слышал голоса, видел всякое... Твоя квартира стала лабиринтом! Радио сводило меня с ума! Но я его разбил. Разбил.",
            "I heard voices, saw all kinds of things... Your apartment turned into a labyrinth! The radio was driving me insane! But I smashed it. Smashed it."),
        ("И твоя записка мне помогла!",
            "And your note helped me!"),
        ("Погоди... А больница? Они хотели тебя оперировать.",
            "Hold on... What about the hospital? They wanted to operate on you."),
        ("Хотели.",
            "They did."),
        ("И?..",
            "And?.."),
        ("Я ушёл.",
            "I left."),
        ("Что?",
            "What?"),
        ("Успел вовремя.",
            "Just in time."),
        ("Подожди. Тебя вообще не удивляет это?",
            "Wait. Doesn't any of this surprise you at all?"),
        ("Что именно?",
            "What exactly?"),
        ("Да всё! Я только что сказал, что нашёл чип! Что видел всякое!",
            "Everything! I just told you I found a chip! That I saw things!"),
        ("Ты же всю жизнь пытался что-то паранормальное разыскать. Книги собирал. Теории строил. И сейчас ты даже ничего не спрашиваешь",
            "Your whole life you tried to dig up something paranormal. Collecting books. Building theories. And now you don't even ask a single question."),
        ("Ты всё понял. Этого достаточно.",
            "You understood everything. That's enough."),
        ("Нет... Нет, не достаточно. Ты бы сейчас уже завалил меня вопросами как это было!",
            "No... No, it's not enough. By now you'd be burying me in questions about how it all happened!"),
        ("Когда это началось? Что было по радио? Как я избавился от чипа?",
            "When did it start? What was on the radio? How did I get rid of the chip?"),
        ("Ты всё знаешь. Ты...",
            "You already know everything. You..."),
    };
}
